### ISSUE TITLE
Seeing Issue why trying to load 

### ISSUE THREAD

**Issue by keshavjha1** [su77ungr/CASALIOY#75] opened 2023-05-17 13:45 UTC
I am facing below problem while running startLLM on Linux/Mac machine 

(.venv) ke2@t2:~/projects/CASALIOY$ python3 casalioy/startLLM.py 
found local model at models/sentence-transformers/all-MiniLM-L6-v2
found local model at models/eachadea/ggml-vicuna-7b-1.1/ggml-vic7b-q5_1.bin
llama.cpp: loading model from models/eachadea/ggml-vicuna-7b-1.1/ggml-vic7b-q5_1.bin
terminate called after throwing an instance of 'std::runtime_error'
  what():  read error: Is a directory
Aborted (core dumped)

**Comment by su77ungr** [comment] 2023-05-17 14:17
What are your machines' specs?

Also this might be an error caused by wrongly specified paths. It tries to run a directory.

Might be fixed with with new PRs. Testing it now.

**Comment by su77ungr** [comment] 2023-05-18 23:41
Has this been resolved?

**Closed** 2023-05-20 01:30 UTC
Labels: bug
